library(shiny)
library(shinydashboard)
library(shinyWidgets)
library(data.table)
library(magrittr)
library(shinyjs)
library(plotly)
library(SummarizedExperiment)
library(dplyr)
library(xlsx)
library(tidyr)
library(tibble)
library(ggplot2)
library(ggpubr)
library(ggrepel)
library(patchwork)
library(shinybusy)
library(spsComps)


source("helper.R")
source("reset_dataset.R")
source("input_file_upload.R")
source("show_file_level_meta.R")
source("plot_missing_per_analyte.R")
source("plot_belowLOD_per_analyte.R")
source("identify_reference.R")
source("ref_normalization.R")
source("creat_data_obj.R")
source("download_qa_report.R")
source("download_norm_report.R")
source("download_combined_data.R")
source("meta_view_replace.R")
source("qc_global_plot.R")
source("scatter_plot.R")
source("download_scatter_report.R")
source("pca_plot.R")
source("download_pca_report.R")
source("cor_summary_plot.R")
source("corr_plot.R")
source("download_cor_report.R")
source("analyte_panel_querry.R")
source("user_select_list.R")

load("olink_all_analyte_panel.rda")

panel_query <- unique(olink_all_analyte_panel$Query)%>%
  strsplit(split = ",")%>%
  unlist()%>%
  unique()
panel_query <- panel_query[panel_query != "NA"]
